name: Restart environment

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.ODS_GITHUB_APP_ID }}
          private-key: ${{ secrets.ODS_GITHUB_PRIVATE_KEY }}
          owner: metadata-swiss
          repositories: |
            opendata-swiss

      - name: Restart environment
        run: gh workflow run restart-ui.yaml --repo metadata-swiss/opendata-swiss -f env="abn"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
